docker-build:
  image: docker:latest
  stage: build

  services:
    - docker:dind

  variables:
    IMAGE: quay.io/mrazimi99/bolbolestan-frontend:$CI_COMMIT_SHA

  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE
